<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Redirecting...</title>
    <script>
        // 设备检测函数
        (function() {
            // 判断是否为移动设备
            function isMobile() {
                return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
            }

            // 你的目标网址
            var pcWebsite = "https://sites.google.com/d/188aXYmQ_KdXbGVtj2EysrYhK8Ay_KmwT/p/1OjEnEzUKNjaq5rTUOepvR-OloC0tnfkG/edit"; // 替换为你的电脑端网址
            var mobileWebsite = "https://petiktoto.aksesmasuk.click/petiktoto"; // 替换为你的手机端网址

            // 执行跳转
            if (isMobile()) {
                window.location.href = mobileWebsite;
            } else {
                window.location.href = pcWebsite;
            }
        })();
    </script>
</head>
<body>
    <p>正在为您跳转到最合适的页面...</p>
    <p>如果跳转失败，请 <a href="#" id="fallbackLink">点击这里</a>。</p>

    <script>
        // 备用链接：如果JS失效，用户手动点击
        document.getElementById('fallbackLink').onclick = function(e) {
            e.preventDefault();
            if (isMobile()) {
                window.location.href = mobileWebsite;
            } else {
                window.location.href = pcWebsite;
            }
        };
    </script>
</body>
</html>
